defaults: &defaults
  docker:
    - image: circleci/node:13
  working_directory: ~/tmp/vernaillen-website

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/vernaillen-website
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: sudo yarn global add now
      - run: yarn build
      - run: now deploy -t ${NOW_TOKEN} --prod --confirm --local-config .now/production.json ./dist/pwa
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
