defaults: &defaults
  docker:
    - image: circleci/node:14
  working_directory: ~/tmp/vernaillen-website

version: 2.1
jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: yarn build
      - sonarcloud/scan
  test:
    steps:
      - run: yarn test:unit
      - run: sudo yarn global add codecov
      - run: codecov
  deploy:
    steps:
      - run: sudo yarn global add now
      - run: now deploy -t ${NOW_TOKEN} --prod --local-config .now/production.json --confirm ./dist/pwa

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          context: SonarCloud
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
