defaults: &defaults
  docker:
    - image: circleci/node:14
  working_directory: /tmp/workspace

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn build-pwa
      - sonarcloud/scan
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn test:unit
      - run: sudo yarn global add codecov
      - run: codecov
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo yarn global add now
      - run: now deploy -t ${NOW_TOKEN} --prod --local-config .now/production.json --confirm ./dist/pwa

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          context: SonarCloud
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
