defaults: &defaults
  docker:
    - image: circleci/node:12-browsers-legacy
  working_directory: ~/tmp/vernaillen-website

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/vernaillen-website
      - run: yarn install
      - run: yarn build
      - sonarcloud/scan
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/vernaillen-website
      - run: yarn test:unit
      - run: sudo yarn global add codecov
      - run: codecov
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/vernaillen-website
      - run: sudo yarn global add now
      - run: now deploy -t ${NOW_TOKEN} --prod --local-config .now/production.json --confirm ./dist/pwa

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          context: SonarCloud
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
